const SpotifyAccessToken = "BQDBwSgu28aZqVy_Kr4zCxvnmcJlVOAwYsfDJi7e_qTpRbMTrJYZt2hRuePMp3zC3WeYk6OFwX1Nc1tI9BNwRyeaEWHnITJTSMzAAP-PWkLHnycPwvlsHF8OLkN7fmWG9rzqv1G2vtY";

export default { SpotifyAccessToken };